/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rockpaperscissors

import com.rockpaperscissors.game.Game


fun main() {
    val game = Game()
    game.playRounds(100)
}
